---
title: FuseDojo Code
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
minimal_mistakes_skin: air
locale: en-US
title_separator: "-"
name: DojoMaster
description: An electronics aficionado and avid web developer. Currently learning
  Javascript
url: https://code.fusedojo.com
baseurl: 
repository: 
teaser: 
breadcrumbs: 
words_per_minute: 200
comments:
  provider: disqus
  disqus:
    shortname: fusedojocode.disqus.com
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields: 
  branch: 
  commitMessage: 
  filename: 
  format: 
  moderation: 
  path: 
  requiredFields: 
  transforms:
    email: 
  generatedFields:
    date:
      type: 
      options:
        format: 
reCaptcha:
  siteKey: 
  secret: 
atom_feed:
  path: 
search: true
search_full_content: 
search_provider: 
algolia:
  application_id: 
  index_name: 
  search_only_api_key: 
  powered_by: 
google:
  search_engine_id: 
  instant_search: 
google_site_verification: 
bing_site_verification: 
yandex_site_verification: 
naver_site_verification: 
twitter:
  username: Fusedojo
facebook:
  username: FuseDojo22
  app_id: 
  publisher: 
og_image: 
social:
  type: 
  name: 
  links: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: 
author:
  name: DojoMaster
  avatar: "/assets/img/Fuselogo.png"
  bio: An electronics aficionado and avid web developer. Currently learning Javascript
  location: Somewhere in cyberspace
  email: dojomaster@fusedojo.com
  uri: https://fusedojo.com
  home: 
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: FuseDojo22
  foursquare: 
  github: FDDojomaster
  gitlab: 
  google_plus: 
  keybase: 
  instagram: dojomasterfd
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: FuseDojo
  vine: 
  weibo: 
  xing: 
  youtube: https://www.youtube.com/channel/UC_TpDOXywPlxFYWUPchGVqA
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
- "/docs"
- "/test"
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
paginate: 5
paginate_path: "/page:num/"
jekyll-archives:
  enabled:
  - year
  - month
  - tags
  layout: archive
  permalinks:
    year: "/:year/"
    month: "/:year/:month/"
    day: "/:year/:month/:day/"
    tag: "/tag/:name/"
    category: "/category/:name/"
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
- jekyll-archives
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
